-- auto-generated definition
create table auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
);

CREATE INDEX auth_group_name_a6ea08ec_like ON auth_group USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX auth_group_name_key ON auth_group USING btree (name);

-- （auth_group 暂无数据，无示例 INSERT）
