-- auto-generated definition
create table auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null,
    permission_id integer not null
);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions USING btree (group_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions USING btree (permission_id);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON auth_group_permissions USING btree (group_id, permission_id);

-- （auth_group_permissions 暂无数据，无示例 INSERT）
