-- auto-generated definition
create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255) not null,
    name    varchar(255) not null,
    applied timestamptz  not null
);

