-- auto-generated definition
create table django_celery_beat_periodictask
(
    id              integer generated by default as identity
        primary key,
    name            varchar(200) not null,
    task            varchar(200) not null,
    args            text         not null,
    kwargs          text         not null,
    queue           varchar(200) null,
    exchange        varchar(200) null,
    routing_key     varchar(200) null,
    expires         timestamptz  null,
    enabled         boolean      not null,
    last_run_at     timestamptz  null,
    total_run_count integer      not null,
    date_changed    timestamptz  not null,
    description     text         not null,
    crontab_id      integer      null,
    interval_id     integer      null,
    solar_id        integer      null,
    one_off         boolean      not null,
    start_time      timestamptz  null,
    priority        integer      null,
    headers         text         not null,
    clocked_id      integer      null,
    expire_seconds  integer      null
);

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON django_celery_beat_periodictask USING btree (clocked_id);

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON django_celery_beat_periodictask USING btree (crontab_id);

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON django_celery_beat_periodictask USING btree (interval_id);

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON django_celery_beat_periodictask USING btree (name varchar_pattern_ops);

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON django_celery_beat_periodictask USING btree (solar_id);

CREATE UNIQUE INDEX django_celery_beat_periodictask_name_key ON django_celery_beat_periodictask USING btree (name);

-- 最新一条数据示例（latest id），已排除生成列，仅供数据构造参考
-- INSERT INTO "django_celery_beat_periodictask" ("id", "name", "task", "args", "kwargs", "queue", "exchange", "routing_key", "expires", "enabled", "last_run_at", "total_run_count", "date_changed", "description", "crontab_id", "interval_id", "solar_id", "one_off", "start_time", "priority", "headers", "clocked_id", "expire_seconds") VALUES (13, 'check-every-day-to-delete-exporter-history', 'plane.bgtasks.exporter_expired_task.delete_old_s3_link', '[]', '{}', NULL, NULL, NULL, NULL, TRUE, '2026-08-18 03:45:00.004584+00:00', 13, '2026-08-18 03:45:10.053596+00:00', '', 12, NULL, NULL, FALSE, NULL, NULL, '{}', NULL, NULL);
