-- auto-generated definition
create table django_celery_beat_clockedschedule
(
    id           integer generated by default as identity
        primary key,
    clocked_time timestamptz not null
);

-- （django_celery_beat_clockedschedule 暂无数据，无示例 INSERT）
