-- auto-generated definition
create table django_celery_beat_crontabschedule
(
    id            integer generated by default as identity
        primary key,
    minute        varchar(240) not null,
    hour          varchar(96)  not null,
    day_of_week   varchar(64)  not null,
    day_of_month  varchar(124) not null,
    month_of_year varchar(64)  not null,
    timezone      varchar(63)  not null
);

