-- auto-generated definition
create table django_celery_beat_intervalschedule
(
    id     integer generated by default as identity
        primary key,
    every  integer     not null,
    period varchar(24) not null
);

