-- auto-generated definition
create table django_celery_beat_clockedschedule
(
    id           integer generated by default as identity
        primary key,
    clocked_time timestamptz not null
);

