-- auto-generated definition
create table project_identifiers
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamptz not null,
    updated_at    timestamptz not null,
    name          varchar(12) not null,
    created_by_id uuid        null,
    project_id    uuid        not null,
    updated_by_id uuid        null,
    workspace_id  uuid        null,
    deleted_at    timestamptz null
);

CREATE INDEX project_identifier_created_by_id_2b6f273a ON project_identifiers USING btree (created_by_id);

CREATE INDEX project_identifier_updated_by_id_1a00e2a0 ON project_identifiers USING btree (updated_by_id);

CREATE INDEX project_identifier_workspace_id_6024b517 ON project_identifiers USING btree (workspace_id);

CREATE INDEX project_identifiers_name_6ca8a4b0 ON project_identifiers USING btree (name);

CREATE INDEX project_identifiers_name_6ca8a4b0_like ON project_identifiers USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX project_identifier_project_id_key ON project_identifiers USING btree (project_id);

CREATE UNIQUE INDEX project_identifiers_name_workspace_id_deleted_at_d332e701_uniq ON project_identifiers USING btree (name, workspace_id, deleted_at);

CREATE UNIQUE INDEX unique_name_workspace_when_deleted_at_null ON project_identifiers USING btree (name, workspace_id) WHERE (deleted_at IS NULL);

-- 最新一条数据示例（latest id），已排除生成列，仅供数据构造参考
-- INSERT INTO "project_identifiers" ("id", "created_at", "updated_at", "name", "created_by_id", "project_id", "updated_by_id", "workspace_id", "deleted_at") VALUES (3, '2026-08-18 06:25:25.064061+00:00', '2026-08-18 06:25:25.064089+00:00', 'PLANE', NULL, 'c274e293-9c4a-4b37-94d8-51afccc1e1d5', NULL, '82345500-e469-419d-843d-92902ffac9db', NULL);
