-- auto-generated definition
create table users_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  uuid    not null,
    group_id integer not null
);

CREATE INDEX user_groups_group_id_b76f8aba ON users_groups USING btree (group_id);

CREATE INDEX user_groups_user_id_abaea130 ON users_groups USING btree (user_id);

CREATE UNIQUE INDEX user_groups_user_id_group_id_40beef00_uniq ON users_groups USING btree (user_id, group_id);

