-- auto-generated definition
create table users_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       uuid    not null,
    permission_id integer not null
);

CREATE INDEX user_user_permissions_permission_id_9deb68a3 ON users_user_permissions USING btree (permission_id);

CREATE INDEX user_user_permissions_user_id_ed4a47ea ON users_user_permissions USING btree (user_id);

CREATE UNIQUE INDEX user_user_permissions_user_id_permission_id_7dc6e2e0_uniq ON users_user_permissions USING btree (user_id, permission_id);

